apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  type: ClusterIP
  selector:
    app: order
  ports:
    - port: 5000
      name: http
      targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
        - name: order
          image: order:latest
          imagePullPolicy: IfNotPresent
          command: ["granian"]
          args: ["--interface", "asgi", "--host", "0.0.0.0", "--port", "5000", "--workers", "2", "--loop", "uvloop", "app:app"]
          ports:
            - containerPort: 5000
          env:
            - name: GATEWAY_URL
              value: "http://gateway:80"
            - name: NATS_URL
              value: "nats://nats:4222"
            - name: REDIS_HOST
              value: order-redis-valkey
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_PASSWORD
              value: "redis"
            - name: REDIS_DB
              value: "0"
            - name: REDIS_SENTINEL_SERVICE
              value: "order-master"
            - name: STOCK_REDIS_HOST
              value: stock-redis-valkey
            - name: STOCK_REDIS_PORT
              value: "6379"
            - name: STOCK_REDIS_PASSWORD
              value: "redis"
            - name: STOCK_REDIS_DB
              value: "0"
            - name: STOCK_REDIS_SENTINEL_SERVICE
              value: "stock-master"
            - name: PAYMENT_REDIS_HOST
              value: payment-redis-valkey
            - name: PAYMENT_REDIS_PORT
              value: "6379"
            - name: PAYMENT_REDIS_PASSWORD
              value: "redis"
            - name: PAYMENT_REDIS_DB
              value: "0"
            - name: PAYMENT_REDIS_SENTINEL_SERVICE
              value: "payment-master"
            - name: SENTINEL_HOSTS
              value: "order-redis-valkey-headless:26379,stock-redis-valkey-headless:26379,payment-redis-valkey-headless:26379"
            - name: INSTANCE_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          resources:
            requests:
              memory: 256Mi
              cpu: 500m
            limits:
              memory: 512Mi
              cpu: 3000m
          startupProbe:
            httpGet:
              path: /health
              port: 5000
            failureThreshold: 12
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            periodSeconds: 10
