apiVersion: v1
kind: Service
metadata:
  name: payment-service
spec:
  type: ClusterIP
  selector:
    app: payment
  ports:
    - port: 5000
      name: http
      targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
    spec:
      containers:
        - name: payment
          image: payment:latest
          imagePullPolicy: IfNotPresent
          command: ["granian"]
          args: ["--interface", "asgi", "--host", "0.0.0.0", "--port", "5000", "--workers", "2", "--loop", "uvloop", "app:app"]
          ports:
            - containerPort: 5000
          env:
            - name: NATS_URL
              value: "nats://nats:4222"
            - name: REDIS_HOST
              value: payment-redis-valkey
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_PASSWORD
              value: "redis"
            - name: REDIS_DB
              value: "0"
            - name: REDIS_SENTINEL_SERVICE
              value: "payment-master"
            - name: SENTINEL_HOSTS
              value: "order-redis-valkey-headless:26379,stock-redis-valkey-headless:26379,payment-redis-valkey-headless:26379"
          resources:
            requests:
              memory: 256Mi
              cpu: 250m
            limits:
              memory: 512Mi
              cpu: 1000m
          startupProbe:
            httpGet:
              path: /health
              port: 5000
            failureThreshold: 12
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            periodSeconds: 10
