auth:
  password: redis
master:
  persistence:
    size: 256Mi
  resources:
    requests:
      memory: 128Mi
      cpu: 100m
    limits:
      memory: 256Mi
      cpu: 250m
replica:
  replicaCount: 0
sentinel:
  enabled: false
