auth:
  password: redis
  sentinel: false
master:
  persistence:
    enabled: true
    size: 256Mi
  resources:
    requests:
      memory: 128Mi
      cpu: 100m
    limits:
      memory: 256Mi
      cpu: 250m
  extraConfig: |
    maxmemory 200mb
    appendfsync everysec
    io-threads 4
    io-threads-do-reads yes
replica:
  replicaCount: 2
  persistence:
    enabled: true
    size: 256Mi
  resources:
    requests:
      memory: 128Mi
      cpu: 100m
    limits:
      memory: 256Mi
      cpu: 250m
  extraConfig: |
    maxmemory 200mb
    appendfsync everysec
sentinel:
  enabled: true
  quorum: 2
  resources:
    requests:
      memory: 64Mi
      cpu: 50m
    limits:
      memory: 128Mi
      cpu: 100m
