sentinel monitor order-master order-db 6379 2
sentinel down-after-milliseconds order-master 5000
sentinel failover-timeout order-master 10000
sentinel parallel-syncs order-master 1
sentinel auth-pass order-master redis
